sudo: false

language: python

python:
    # FIXME: Not sure why this suddenly doesn't work on Travis anymore.
    #- "2.7"
    - "pypy3"
    - "3.6"
    - "nightly"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install 3to2; fi
    - python setup.py install

    # Prevent Python 2.7 from using the non-3to2 converted code.
    - mv language_check .language_check

    - pip install pycodestyle pylint rstcheck

script:
    # FIXME: Re-enable when we make this find a unique port to run on.
    #        Currently, it sometimes fails on Travis.
    #- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./test_remote.bash; fi

    - ./test.py

    - ./run_doctest.py -v download_lt.py
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.7" ]; then ./run_doctest.py -v README.rst; fi

    - ./test.bash

    # Smoke test.
    - echo 'This is a sentence.' > foo.txt
    - language-check foo.txt
    - language-check --version

    - mv .language_check language_check
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then make check; fi
