sudo: false

language: python

python:
    - "2.7"
    - "pypy3"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install 3to2; fi
    - python setup.py --quiet install

    # Prevent Python 2.7 from using the non-3to2 converted code.
    - mv language_check .language_check

script:
    - ./test.py

    - ./run_doctest.py -v download_lt.py
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.7" ]; then ./run_doctest.py -v README.rst; fi

    - bash test.bash

    # Smoke test.
    - echo 'This is a sentence.' > foo.txt
    - language-check foo.txt
    - language-check --version
